using System.Text;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using SImageGen.Data;
using SImageGen.Services;

var builder = WebApplication.CreateBuilder(args);

// Render provides $PORT; default 8080 for local/Docker.
var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
builder.WebHost.UseUrls($"http://*:{port}");

builder.Services.AddControllersWithViews();
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(o =>
    {
        o.LoginPath = "/Account/Login";
        o.ExpireTimeSpan = TimeSpan.FromDays(30);
        o.SlidingExpiration = false;   // lets an idle free-tier instance sleep
        o.Cookie.Name = "simagegen.auth";
        o.Cookie.HttpOnly = true;
    });

// Neon hands out URLs with query keys Npgsql rejects (channel_binding) and pooler
// keys that mean the opposite thing to an Npgsql pool (pooling). Normalise both.
static string NormalizeConnectionString(string? raw)
{
    if (string.IsNullOrWhiteSpace(raw)) return "";

    if (Uri.TryCreate(raw.Trim().Replace("postgresql://", "postgres://", StringComparison.Ordinal),
                      UriKind.Absolute, out var uri))
    {
        var b = new StringBuilder("Host=").Append(uri.Host)
            .Append(";Port=").Append(uri.IsDefaultPort ? 5432 : uri.Port)
            .Append(";Database=").Append(uri.AbsolutePath.Trim('/'))
            .Append(";Username=").Append(Uri.UnescapeDataString(uri.UserInfo.Split(':')[0]));

        if (uri.UserInfo.Contains(':'))
            b.Append(";Password=").Append(Uri.UnescapeDataString(uri.UserInfo.Split(':', 2)[1]));

        b.Append(";SSL Mode=Require");

        var q = System.Web.HttpUtility.ParseQueryString(uri.Query);
        if (q["sslmode"] is { Length: > 0 } s) b.Append(";SSL Mode=").Append(s);
        // NOTE: channel_binding is intentionally NOT mapped: TrustServerCertificate
        // is obsolete (no-op) in Npgsql 10, so mapping it would only add a warning.

        // A pool size of 2 keeps Npgsql's memory tiny; this host has 0.1 CPU anyway.
        b.Append(";Maximum Pool Size=2;Minimum Pool Size=0;Timeout=15;Command Timeout=30");
        return b.ToString();
    }

    return raw.Trim();
}

var conn = NormalizeConnectionString(
    Environment.GetEnvironmentVariable("DATABASE_URL")
    ?? builder.Configuration.GetConnectionString("Default"));

if (!string.IsNullOrWhiteSpace(conn))
{
    builder.Services.AddDbContext<AppDbContext>(o => o.UseNpgsql(conn));
}
else
{
    // Keep the app bootable without a database so /healthz can still answer.
    builder.Services.AddDbContext<AppDbContext>(o => o.UseNpgsql(
        "Host=localhost;Database=simagegen;Username=postgres;Password=postgres"));
}

builder.Services.AddHttpClient<PollinationsClient>(c => c.Timeout = TimeSpan.FromMinutes(10));
builder.Services.AddHttpClient<CustomModelClient>(c => c.Timeout = TimeSpan.FromMinutes(20));
builder.Services.AddSingleton<BackendSelector>();
builder.Services.AddScoped<QuotaService>();
builder.Services.AddSingleton<ImageStore>();
builder.Services.AddSingleton<GenerationQueue>();
builder.Services.AddHostedService(sp => sp.GetRequiredService<GenerationQueue>());

// Per-IP fixed windows on the auth endpoints (free tier has no WAF).
builder.Services.AddRateLimiter(o =>
{
    o.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
    o.AddFixedWindowLimiter("auth-login", x =>
    {
        x.PermitLimit = 5;
        x.Window = TimeSpan.FromMinutes(5);
        x.QueueLimit = 0;
    });
    o.AddFixedWindowLimiter("auth-register", x =>
    {
        x.PermitLimit = 3;
        x.Window = TimeSpan.FromHours(1);
        x.QueueLimit = 0;
    });
});

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    try
    {
        await db.Database.MigrateAsync();
        app.Logger.LogInformation("Database migrated");
    }
    catch (Exception ex)
    {
        // Neon scales to zero after 5 min; the first query can be slow or fail.
        app.Logger.LogWarning(ex, "Database unavailable at startup; continuing");
    }

    // Belt-and-suspenders: tables must exist even when MigrateAsync above
    // throws halfway. IF NOT EXISTS makes this a safe no-op on healthy databases.
    // (Quota enforcement fails open; generation fails with a clear error.)
    try
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Users" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Username" character varying(32) NOT NULL,
                "PasswordHash" text NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                "DailyQuota" integer NOT NULL,
                "IsActive" boolean NOT NULL,
                CONSTRAINT "PK_Users" PRIMARY KEY ("Id"));
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Username" ON "Users" ("Username");
            CREATE TABLE IF NOT EXISTS "DailyUsages" (
                "UserId" integer NOT NULL,
                "Day" date NOT NULL,
                "Count" integer NOT NULL,
                CONSTRAINT "PK_DailyUsages" PRIMARY KEY ("UserId", "Day"));
            CREATE TABLE IF NOT EXISTS "Generations" (
                "Id" uuid NOT NULL,
                "UserId" integer NOT NULL,
                "Mode" character varying(8) NOT NULL,
                "Prompt" character varying(500) NOT NULL,
                "Seed" integer NOT NULL,
                "Size" character varying(16) NOT NULL,
                "Model" character varying(64) NOT NULL,
                "PromptHash" character varying(64) NOT NULL,
                "ImageUrl" text,
                "InputImageUrl" text,
                "Status" character varying(16) NOT NULL,
                "Error" text,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_Generations" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_Generations_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE);
            CREATE INDEX IF NOT EXISTS "IX_Generations_PromptHash" ON "Generations" ("PromptHash");
            CREATE INDEX IF NOT EXISTS "IX_Generations_UserId_CreatedAtUtc" ON "Generations" ("UserId", "CreatedAtUtc");
            """);
        app.Logger.LogInformation("Tables ensured");
    }
    catch (Exception ex)
    {
        app.Logger.LogWarning(ex, "Tables not ensured; DB operations may fail until Neon wakes");
    }
}

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
}
app.UseStaticFiles();
app.UseRouting();
app.UseRateLimiter();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
app.MapGet("/healthz", () => Results.Json(new
{
    ok = true,
    // Remote diagnostics: which backend is active and which build is live.
    backend = SImageGen.Services.BackendSelector.Mode,
    custom = SImageGen.Services.BackendSelector.CustomConfigured,
    build = Environment.GetEnvironmentVariable("RENDER_GIT_COMMIT") is { Length: > 0 } sha
        ? sha[..Math.Min(7, sha.Length)]
        : "local",
    time = DateTime.UtcNow
}));

app.Run();
