CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001105115_InitialCreate') THEN
    CREATE TABLE "DailyUsages" (
        "UserId" integer NOT NULL,
        "Day" date NOT NULL,
        "Count" integer NOT NULL,
        CONSTRAINT "PK_DailyUsages" PRIMARY KEY ("UserId", "Day")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001105115_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(32) NOT NULL,
        "PasswordHash" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "DailyQuota" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001105115_InitialCreate') THEN
    CREATE TABLE "Generations" (
        "Id" uuid NOT NULL,
        "UserId" integer NOT NULL,
        "Mode" character varying(8) NOT NULL,
        "Prompt" character varying(500) NOT NULL,
        "Seed" integer NOT NULL,
        "Size" character varying(16) NOT NULL,
        "Model" character varying(64) NOT NULL,
        "PromptHash" character varying(64) NOT NULL,
        "ImageUrl" text,
        "InputImageUrl" text,
        "Status" character varying(16) NOT NULL,
        "Error" text,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Generations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Generations_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001105115_InitialCreate') THEN
    CREATE INDEX "IX_Generations_PromptHash" ON "Generations" ("PromptHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001105115_InitialCreate') THEN
    CREATE INDEX "IX_Generations_UserId_CreatedAtUtc" ON "Generations" ("UserId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001105115_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001105115_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261001105115_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001152806_ChatThreads') THEN
    ALTER TABLE "Generations" ADD "ConversationId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001152806_ChatThreads') THEN
    CREATE TABLE "Conversations" (
        "Id" uuid NOT NULL,
        "UserId" integer NOT NULL,
        "Title" character varying(120) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Conversations_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001152806_ChatThreads') THEN
    CREATE TABLE "Messages" (
        "Id" uuid NOT NULL,
        "ConversationId" uuid NOT NULL,
        "Role" character varying(16) NOT NULL,
        "TextContent" text,
        "ImageUrl" text,
        "GenerationId" uuid,
        "Status" character varying(16) NOT NULL,
        "Error" text,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001152806_ChatThreads') THEN
    CREATE INDEX "IX_Conversations_UserId_CreatedAtUtc" ON "Conversations" ("UserId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001152806_ChatThreads') THEN
    CREATE INDEX "IX_Messages_ConversationId_CreatedAtUtc" ON "Messages" ("ConversationId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261001152806_ChatThreads') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261001152806_ChatThreads', '10.0.12');
    END IF;
END $EF$;
COMMIT;

